### ISSUE TITLE
Create a common function for reading release files

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodeSDK#232]
Release files (`setup-wizard.yml` `dappnode_package.json` `docker-compose.yml` `getting_started.yml` etc) are widely read across the SDK code base, this is confusing and not optimized

Instead, it should be read with one function taking into account:
- Get the release file path
- If it is a mandatory file or not (only manifest wizard and compose), throw the corresponding error

**Comment by dapplion** [comment]
As discussed offline we shouldn't be reading files that much to begin with.

- Manifest should be read once and then passed around as a variable
- Compose should only be read if it has to be mutated for build purposes. Otherwise just read to validate and drop the variable
- setup-wizard.yml read to validate and drop variable
- getting_started.yml is this read somewhere? Why should we read it?

**Comment by pablomendezroyo** [comment]
won't implement
